//user login
export const FETCHING_USER = 'FETCHING_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const CLEAR_USER_STORE = 'CLEAR_USER_STORE';
export const EDIT_USER_KEYS = 'EDIT_USER_KEYS'
export const USER_LOGOUT = 'USER_LOGOUT'
// generating keys
export const GENERATING_APIKEYS_SUCCESS = 'GENERATING_APIKEYS_SUCCESS'
export const GENERATING_APIKEYS_FAIL = 'GENERATING_APIKEYS_FAIL'
export const START_GENERATING_APIKEYS = 'START_GENERATING_APIKEYS'
export const CLEAR_KEYS_STORE = 'CLEAR_KEYS_STORE';
